### ISSUE TITLE
package registry

### ISSUE THREAD

**Issue by alexriss** [lnacquaroli/SavitzkyGolay.jl#19]
Have you considered registering your package in the Julia package registry? It would make it easier for other people (such as me) to use your package in their projects. Do you need support with that?

**Comment by lnacquaroli** [comment]
Hi, thanks for reaching out, and sorry for the late response. 

Please, feel free to do it as I am currently overcommitted. Otherwise, let me know if you need any help, I will try to answer faster.

Cheers!

**Comment by lnacquaroli** [comment]
@JuliaRegistrator register()

**Comment by lnacquaroli** [comment]
@JuliaRegistrator register()

**Comment by lnacquaroli** [comment]
@JuliaRegistrator register()

**Comment by lnacquaroli** [comment]
@JuliaRegistrator register()

**Comment by lnacquaroli** [comment]
@JuliaRegistrator register()

**Comment by lnacquaroli** [comment]
@alexriss done!

https://github.com/JuliaRegistries/General/pull/58632

**Comment by alexriss** [comment]
That is great, thank you for your efforts!
