### ISSUE TITLE
Derivative needs scaling (use of 'Rate')

### ISSUE THREAD

**Issue by williamhunter** [lnacquaroli/SavitzkyGolay.jl#23]
Hi, firstly, thanks for coding this.

I'm using the filter to determine the derivative of some experimental data. I noticed that I have to scale the 'y' values of the derivative as per below:
```julia
start=-5; stop=15; le=200; ord=3; der=1;

x = LinRange(start, stop, le)
y = 0.15*x.^3 - 2*x.^2 + x  .+ randn(length(x))
y1 = 0.45*x.^2 - 4*x .+ 1
sg = savitzky_golay(y, 21, ord, deriv=der)
plot(x, [y y1 le/(stop-start)^d*sg.y], label=["Poly with noise" "Exact derivative of poly" "Derivative from SG"], legend_position = :bottomleft)
```
![2022-06-13 13_45_59-Example of use Savitzky-Golay Filter](https://user-images.githubusercontent.com/14232913/173346883-37cf4303-5d50-4c95-93a5-3fc76758e8ef.png)
Alternatively, I can use 'Rate' as I did here (using the inputs from block above):
```julia
sg = savitzky_golay(y, 21, ord, deriv=der, rate=le/(stop-start)^der)
plot(x, [y y1 sg.y], label=["Original signal" "Exact derivative" "Filtered derivative"], legend_position = :bottomleft)
```

The results are identical.

I couldn't find any help on the use of the 'Rate' parameter, just wanted to check if that is the intended use?

Regards,
William

**Comment by lnacquaroli** [comment]
Hi! Thanks for reaching out.

This is what I get with the code you provided:

```julia
using SavitzkyGolay
using GLMakie

start = -5
stop = 15
le = 200
ord = 3
der = 1
rate = le/(stop-start)
ws = 21

x = LinRange(start, stop, le)
data = 0.15*x.^3 - 2*x.^2 + x  .+ randn(length(x))
deriv_exact = 0.45*x.^2 - 4*x .+ 1
sg = savitzky_golay(data, ws, ord, deriv=der)
sg_rate = savitzky_golay(data, ws, ord, deriv=der, rate=rate)

lines(x, data, label="Data")
lines!(x, deriv_exact, label="Exact derivative")
lines!(x, sg.y, label="SG")
lines!(x, sg_rate.y, label="SG with rate")
axislegend()
current_figure()
``` 

![output](https://user-images.githubusercontent.com/26485264/173628241-fea71516-8b85-4182-b272-fcf77ebdeac5.png)

So, I am not sure why it doesn't work on your side. 

Let me know if the problem persists.

**Comment by williamhunter** [comment]
Hi, I didn't explain my 'issue' (it's more of a help question) properly, sorry.

With reference to your example code above, I would've expected that `sg = savitzky_golay(data, ws, ord, deriv=der)` (SG) would give the same result as `sg_rate = savitzky_golay(data, ws, ord, deriv=der, rate=rate)` (SG with rate), but it doesn't. One has to include the `rate` keyword argument to get the correct result for the derivative. I just wanted to confirm if that is indeed the intended use of `rate`?

It's also not clear from the source/help what `rate` is supposed to do, or where to use it.

Is it an option to automatically add the default 'scaling' `(rate = le/(stop-start))` to the `rate` keyword?

**Comment by lnacquaroli** [comment]
> Is it an option to automatically add the default 'scaling' (rate = le/(stop-start)) to the rate keyword?

Yes, it is. It is built this way. See [`scipy`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.savgol_filter.html) implementation also.


> It's also not clear from the source/help what rate is supposed to do, or where to use it.

Thanks, will work on it.

**Comment by williamhunter** [comment]
Thanks. Perhaps easiest just to hard code the `rate` value to be equal to `le/(stop-start)` since users would normally expect the derivative to be correct out of the box.

**Comment by lnacquaroli** [comment]
It could be an option, yes. I will keep it in mind. Thanks!

**Comment by lnacquaroli** [comment]
Notice that for that option you will need to input the values of `x` though, otherwise, it cannot estimate the scaling.
