### ISSUE TITLE
Signal padding for matching start and end points

### ISSUE THREAD

**Issue by janbruedigam** [lnacquaroli/SavitzkyGolay.jl#27]
Cool package!
I'm trying to understand the `_padding_signal` function [here](https://github.com/lnacquaroli/SavitzkyGolay.jl/blob/8b6cec414511903df2d95a3f3d6273d0b44954ab/src/SavitzkyGolay.jl#L94C2-L94C2).

Why do you take the `abs` values of the difference for padding, and why do you add the padding to the end values instead of subtracting?
I'm trying to get the smoothed signal to match the start and end point of the original filter, and when I change these two things, it works. 
Just wondering if doing it my way breaks something else?

**Comment by lnacquaroli** [comment]
Thanks for the message.

If you have an MWE would be useful. The padding is just to match the implementation here: https://scipy-cookbook.readthedocs.io/items/SavitzkyGolay.html.

**Comment by janbruedigam** [comment]
Here's a MWE:

```julia
using SavitzkyGolay, Plots

w = 3
o = 1

# Non-matching start point

x = [1;0;1]
plot(x)
plot!(savitzky_golay(x,w,o).y)


# Non-matching end point

x = [0;1;0]
plot(x)
plot!(savitzky_golay(x,w,o).y)


# Matching start and end point with modified padding

function SavitzkyGolay._padding_signal(y::AbstractVector, hw::Int64)
    initvals = y[1] .- (reverse(y[2:hw+1]) .- y[1])
    endvals = y[end] .- reverse(y[end-hw:end-1] .- y[end])
    return vcat(initvals, y, endvals)
end

x = [1;0;1]
plot(x)
plot!(savitzky_golay(x,w,o).y)

x = [0;1;0]
plot(x)
plot!(savitzky_golay(x,w,o).y)
```

**Comment by lnacquaroli** [comment]
A new tag was created. The tagbot should add it soon. Thanks!
